version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes:
      - ./infra/initdb:/docker-entrypoint-initdb.d

  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker:latest
    environment:
      AMQ_USER: admin
      AMQ_PASSWORD: admin
    ports: ["61616:61616", "8161:8161"] # JMS + console web

  zipkin:
    image: openzipkin/zipkin:3
    ports: ["9411:9411"]

  # (Approche B) Keycloak — activer si nécessaire
  # keycloak:
  #   image: quay.io/keycloak/keycloak:24.0
  #   command: ["start-dev", "--http-port=8082"]
  #   environment:
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: admin
  #   ports: ["8082:8082"]
